import type { Metadata } from 'next';
import { Edu_VIC_WA_NT_Beginner } from 'next/font/google';
import './globals.css';
import ClientProvider from '@/components/common/ClientProvider';
import { getSession } from '@/pages/api/auth/[...nextauth]';

const inter = Edu_VIC_WA_NT_Beginner({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const server_session = getSession();

	return (
		<html lang="en">
			<ClientProvider session={server_session}>
				<body className={inter.className}>{children}</body>
			</ClientProvider>
		</html>
	);
}
